/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/database/': RouteRecordInfo<'/database/', '/database', Record<never, never>, Record<never, never>>,
    '/database/ds/': RouteRecordInfo<'/database/ds/', '/database/ds', Record<never, never>, Record<never, never>>,
    '/database/oop/': RouteRecordInfo<'/database/oop/', '/database/oop', Record<never, never>, Record<never, never>>,
    '/database/oop/00.熟悉环境': RouteRecordInfo<'/database/oop/00.熟悉环境', '/database/oop/00/熟悉环境', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/C++/🚀 深入理解 C++20 bit：现代位操作的终极指南': RouteRecordInfo<'/posts/C++/🚀 深入理解 C++20 bit：现代位操作的终极指南', '/posts/C++/🚀 深入理解 C++20 bit：现代位操作的终极指南', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy': RouteRecordInfo<'/posts/hello-valaxy', '/posts/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/算法与数据结构/4+ 高阶数据结构': RouteRecordInfo<'/posts/算法与数据结构/4+ 高阶数据结构', '/posts/算法与数据结构/4+ 高阶数据结构', Record<never, never>, Record<never, never>>,
    '/posts/线性代数/矩阵': RouteRecordInfo<'/posts/线性代数/矩阵', '/posts/线性代数/矩阵', Record<never, never>, Record<never, never>>,
    '/posts/线性代数/行列式': RouteRecordInfo<'/posts/线性代数/行列式', '/posts/线性代数/行列式', Record<never, never>, Record<never, never>>,
    '/posts/题解/abc396 题解': RouteRecordInfo<'/posts/题解/abc396 题解', '/posts/题解/abc396 题解', Record<never, never>, Record<never, never>>,
    '/posts/题解/abc397 题解': RouteRecordInfo<'/posts/题解/abc397 题解', '/posts/题解/abc397 题解', Record<never, never>, Record<never, never>>,
    '/posts/题解/SZTU_ACM新生夏令营第一次训练赛': RouteRecordInfo<'/posts/题解/SZTU_ACM新生夏令营第一次训练赛', '/posts/题解/SZTU_ACM新生夏令营第一次训练赛', Record<never, never>, Record<never, never>>,
    '/posts/题解/SZTU_ACM新生夏令营第四次训练赛': RouteRecordInfo<'/posts/题解/SZTU_ACM新生夏令营第四次训练赛', '/posts/题解/SZTU_ACM新生夏令营第四次训练赛', Record<never, never>, Record<never, never>>,
    '/problems/': RouteRecordInfo<'/problems/', '/problems', Record<never, never>, Record<never, never>>,
    '/problems/八数码': RouteRecordInfo<'/problems/八数码', '/problems/八数码', Record<never, never>, Record<never, never>>,
    '/problems/最大上升子序列和': RouteRecordInfo<'/problems/最大上升子序列和', '/problems/最大上升子序列和', Record<never, never>, Record<never, never>>,
    '/problems/凸多边形的划分': RouteRecordInfo<'/problems/凸多边形的划分', '/problems/凸多边形的划分', Record<never, never>, Record<never, never>>,
    '/problems/友好城市': RouteRecordInfo<'/problems/友好城市', '/problems/友好城市', Record<never, never>, Record<never, never>>,
    '/problems/合并石子': RouteRecordInfo<'/problems/合并石子', '/problems/合并石子', Record<never, never>, Record<never, never>>,
    '/problems/奶酪': RouteRecordInfo<'/problems/奶酪', '/problems/奶酪', Record<never, never>, Record<never, never>>,
    '/problems/拦截导弹': RouteRecordInfo<'/problems/拦截导弹', '/problems/拦截导弹', Record<never, never>, Record<never, never>>,
    '/problems/方格取数': RouteRecordInfo<'/problems/方格取数', '/problems/方格取数', Record<never, never>, Record<never, never>>,
    '/problems/校门外的树（增强版）': RouteRecordInfo<'/problems/校门外的树（增强版）', '/problems/校门外的树（增强版）', Record<never, never>, Record<never, never>>,
    '/problems/石子合并': RouteRecordInfo<'/problems/石子合并', '/problems/石子合并', Record<never, never>, Record<never, never>>,
    '/problems/租用游艇': RouteRecordInfo<'/problems/租用游艇', '/problems/租用游艇', Record<never, never>, Record<never, never>>,
    '/problems/能量项链': RouteRecordInfo<'/problems/能量项链', '/problems/能量项链', Record<never, never>, Record<never, never>>,
    '/problems/解题笔记': RouteRecordInfo<'/problems/解题笔记', '/problems/解题笔记', Record<never, never>, Record<never, never>>,
    '/projects/': RouteRecordInfo<'/projects/', '/projects', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.26.3_vue@3.5.19_typescript@5.9.2_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes: '/'
      views: never
    }
    'node_modules/.pnpm/valaxy@0.26.3_@babel+parser@7.28.3_@nuxt+kit@3.18.1_@types+markdown-it@14.1.2_@types+no_9182ce1915e86a294eabd31378eb4f34/node_modules/valaxy/client/pages/[...path].vue': {
      routes: '/[...path]'
      views: never
    }
    'pages/404.md': {
      routes: '/404'
      views: never
    }
    'pages/about/index.md': {
      routes: '/about/'
      views: never
    }
    'pages/about/site.md': {
      routes: '/about/site'
      views: never
    }
    'pages/archives/index.md': {
      routes: '/archives/'
      views: never
    }
    'pages/categories/index.md': {
      routes: '/categories/'
      views: never
    }
    'pages/database/index.md': {
      routes: '/database/'
      views: never
    }
    'pages/database/ds/index.md': {
      routes: '/database/ds/'
      views: never
    }
    'pages/database/oop/index.md': {
      routes: '/database/oop/'
      views: never
    }
    'pages/database/oop/00.熟悉环境.md': {
      routes: '/database/oop/00.熟悉环境'
      views: never
    }
    'pages/links/index.md': {
      routes: '/links/'
      views: never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.26.3_vue@3.5.19_typescript@5.9.2_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes: '/page/[page]'
      views: never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.26.3_vue@3.5.19_typescript@5.9.2_/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes: '/posts/'
      views: never
    }
    'pages/posts/C++/🚀 深入理解 C++20 bit：现代位操作的终极指南.md': {
      routes: '/posts/C++/🚀 深入理解 C++20 bit：现代位操作的终极指南'
      views: never
    }
    'pages/posts/hello-valaxy.md': {
      routes: '/posts/hello-valaxy'
      views: never
    }
    'pages/posts/算法与数据结构/4+ 高阶数据结构.md': {
      routes: '/posts/算法与数据结构/4+ 高阶数据结构'
      views: never
    }
    'pages/posts/线性代数/矩阵.md': {
      routes: '/posts/线性代数/矩阵'
      views: never
    }
    'pages/posts/线性代数/行列式.md': {
      routes: '/posts/线性代数/行列式'
      views: never
    }
    'pages/posts/题解/abc396 题解.md': {
      routes: '/posts/题解/abc396 题解'
      views: never
    }
    'pages/posts/题解/abc397 题解.md': {
      routes: '/posts/题解/abc397 题解'
      views: never
    }
    'pages/posts/题解/SZTU_ACM新生夏令营第一次训练赛.md': {
      routes: '/posts/题解/SZTU_ACM新生夏令营第一次训练赛'
      views: never
    }
    'pages/posts/题解/SZTU_ACM新生夏令营第四次训练赛.md': {
      routes: '/posts/题解/SZTU_ACM新生夏令营第四次训练赛'
      views: never
    }
    'pages/problems/index.md': {
      routes: '/problems/'
      views: never
    }
    'pages/problems/八数码.md': {
      routes: '/problems/八数码'
      views: never
    }
    'pages/problems/最大上升子序列和.md': {
      routes: '/problems/最大上升子序列和'
      views: never
    }
    'pages/problems/凸多边形的划分.md': {
      routes: '/problems/凸多边形的划分'
      views: never
    }
    'pages/problems/友好城市.md': {
      routes: '/problems/友好城市'
      views: never
    }
    'pages/problems/合并石子.md': {
      routes: '/problems/合并石子'
      views: never
    }
    'pages/problems/奶酪.md': {
      routes: '/problems/奶酪'
      views: never
    }
    'pages/problems/拦截导弹.md': {
      routes: '/problems/拦截导弹'
      views: never
    }
    'pages/problems/方格取数.md': {
      routes: '/problems/方格取数'
      views: never
    }
    'pages/problems/校门外的树（增强版）.md': {
      routes: '/problems/校门外的树（增强版）'
      views: never
    }
    'pages/problems/石子合并.md': {
      routes: '/problems/石子合并'
      views: never
    }
    'pages/problems/租用游艇.md': {
      routes: '/problems/租用游艇'
      views: never
    }
    'pages/problems/能量项链.md': {
      routes: '/problems/能量项链'
      views: never
    }
    'pages/problems/解题笔记.md': {
      routes: '/problems/解题笔记'
      views: never
    }
    'pages/projects/index.md': {
      routes: '/projects/'
      views: never
    }
    'pages/tags/index.md': {
      routes: '/tags/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
